### ISSUE TITLE
OpenVPN IP Reservation Improvement

### ISSUE THREAD

**Issue by andre8244** [NethServer/nethsecurity#678]
## Description
Improve the handling of reserved IPs in OpenVPN configuration to prevent conflicts between reserved IPs and dynamically assigned IPs from the pool.

## Tasks
- [x] Design UI changes to allow configuration of IP pool range
- [x] Implement backend changes to support custom IP pool range
- [x] Update API to handle new configuration options
- [x] Implement UI changes based on approved design
- [x] Add validation for IP range and reservations
- [x] Update migration process to handle existing configurations
- [x] Update documentation to reflect new features and best practices
- [x] Implement changes for both new and existing OpenVPN servers
- [x] Test thoroughly, especially migration scenarios and edge cases

## Considerations
- Default behavior should change for new installations (pool 50-254)
- Migration from NS7 may require manual reconfiguration of IP assignments
- New feature should be presented as an advanced option
- Consider using network objects to assist with migrations

**Comment by andre8244** [comment]
**Test case 1**
- Install NethSecurity from scratch
- Go to **VPN > OpenVPN Road Warrior**
- Click **Create server**
- Verify that the default value of **Dynamic range IP start**:
  - Belongs to the network specified in **VPN network** field
  - The last octet is "50", e.g. "10.218.130.50"
- Verify that the default value of **Dynamic range IP end**:
  - Belongs to the network specified in **VPN network** field
  - The last octet is "254", e.g. "10.218.130.254"
- Enter the required fields to configure the VPN server
- Edit the values of **Dynamic range IP start** and **Dynamic range IP end** and click **Create**
- Reopen the server drawer by clicking **Edit**
- Verify that **Dynamic range IP start** and **Dynamic range IP end** show the values you entered on server creation

**Comment by andre8244** [comment]
**Test case 2**
- Migrate to NethSecurity from a NethServer 7 installation with a OpenVPN server configured
- Go to **VPN > OpenVPN Road Warrior**
- Click **Edit** to review server configuration
- Verify that the value of **Dynamic range IP start**:
  - Belongs to the network specified in **VPN network** field
  - The last octet is "2", e.g. "10.218.130.2"
- Verify that the value of **Dynamic range IP end**:
  - Belongs to the network specified in **VPN network** field
  - The last octet is "254", e.g. "10.218.130.254"

**Comment by andre8244** [comment]
Testing image version: [8-23.05.4-ns.1.1.99-alpha1-7-gcd67e08](https://updates.nethsecurity.nethserver.org/dev/8-23.05.4-ns.1.1.99-alpha1-7-gcd67e08/targets/x86/64/nethsecurity-8-23.05.4-ns.1.1.99-alpha1-7-gcd67e08-x86-64-generic-squashfs-combined-efi.img.gz)

**Comment by cotosso** [comment]
**Test Case 1**
everything went fine, no problems found.
Reservation worked as expected.

**Comment by cotosso** [comment]
**Test Case 2**
Migrated configuration correctly has a dynamic range between 2 and 254 (last octet)
